basicApp/urls.py
from django.urls import path
from basicApp import views

app_name = 'basicApp'
urlpatterns = [

    path('registration/', views.registrationPage, name='registration'),
    path('login/', views.loginPage, name='login'),
]

learningUsers/urls.py
from django.contrib import admin
from django.urls import path, include
from basicApp import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basicApp/', include(('basicApp.urls', 'basicApp'),
                              namespace='basicApp')),
    path('logout/', views.logOutPage, name='logout'),
    path('special/', views.special, name='special'),
]

basicApp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class userProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Additional fields
    profilePic = models.ImageField(upload_to='profilePicDir', blank=True)
    portfolio = models.URLField(blank=True)

    def __str__(self):
        return self.user.username

basicApp/forms.py
from django import forms
from basicApp.models import userProfileInfo
from django.contrib.auth.models import User

class userForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password', 'email')


class userProfileInfoForm(forms.ModelForm):

    class Meta:
        model = userProfileInfo
        fields = ('portfolio', 'profilePic')

basicApp/views.py
from django.shortcuts import render

# Create your views here.
from basicApp import forms

# login imports
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request, 'basicApp/index.html')


def registrationPage(request):
    isRegistered = False
    if request.method == 'POST':
        userFormObj = forms.userForm(data=request.POST)
        profileFormObj = forms.userProfileInfoForm(data=request.POST)

        if userFormObj.is_valid() and profileFormObj.is_valid():
            user = userFormObj.save()
            user.set_password(user.password)
            user.save()
            profile = profileFormObj.save(commit=False)
            profile.user = user
            if 'profilePic' in request.FILES:
                print('Profile Picture Found.')
                profile.profilePic = request.FILES['profilePic']
            profile.save()
            isRegistered = True
        else:
            print(userFormObj.errors, profileFormObj.errors)
    else:
        userFormObj = forms.userForm()
        profileFormObj = forms.userProfileInfoForm()
    formDict = {'userForm': userFormObj, 'profileForm': profileFormObj,
                'isRegistered': isRegistered}
    return render(request, 'basicApp/registration.html', context=formDict)


def loginPage(request):
    if request.method == 'POST':
        userName = request.POST.get('username')
        passWord = request.POST.get('password')

        # using django built-in authentication function.
        user = authenticate(username=userName, password=passWord)
        if user:
            if user.is_active:
                login(request, user) # login function.
                return HttpResponseRedirect(reverse(index))
            # redirect to home page.
            else:
                # print some statement.
                return HttpResponse('ACCOUNT NOT ACTIVE')
        else:
            print("SOMEONE TRIED TO LOGIN AND FAILED")
            print("USERNAME:",userName, "PASSWORD: ", passWord)
            return HttpResponse('INVALID LOGIN DETAILS PROVIDED.')

    else:
        return render(request, 'basicApp/login.html', {})

@login_required
def logOutPage(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("You are Loggedin. NICE!!!")

templates/base.html
<html>
<head>
    
    <meta charset="utf-8">
    <title>Navbar</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
<body>
    
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark"> <!-- navbar-dark and bg-dark are for navbar color, navbar expand-sm is used so that all the items are visible till the small screen, doesn't work for small screen -->
        <div class="container">
  <a class="navbar-brand" href="#">Navbar</a>
            
            <button class="navbar-toggler" data-toggle="collapse" aria-controls="togglebutton" data-target="#togglebutton">  
                <!-- for nav items to be seen on small screen, add an icon (burger item) using button and put a class in span tag, but still links won't work, so we add data-toggle and data-target element in button tag which uses js library-->
                
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="togglebutton"> <!--  don't be seen as a list in downside-->
            <ul class="navbar-nav mr-auto"> <!-- margin left automatically puts items on the left side. -->
            <li class="nav-item"><a href="{% url 'basicApp:index' %}" class="nav-link" >Index </a></li> 
     <!-- specify nav links for merge in navbar, otherwise they will be visible as a simple blue links. -->
            <li class="nav-item"><a href="{% url 'basicApp:registration' %}" class="nav-link" >Register Here</a></li>
            <li class="nav-item"><a href="{% url 'basicApp:login' %}" class="nav-link" >Login</a></li>
                <!-- dropdown menu in navbar -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="id_1" data-toggle="dropdown">Dropdown Menu</a>
                <div class="dropdown-menu" id="id_1">
                    <a class="dropdown-item" href="https://www.google.co.in">Go to Google</a>
                    <a class="dropdown-item" href="https://www.youtube.com">Go to Youtube</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="navbar.html">Return to Homepage</a>
                    
            <li class="nav-item"><a class="nav-link disabled">Don't touch </a></li>
                </div>
                </li>
            </ul>
                
            <form class="form-inline">
                <input class="form-control mt-2 " type="search" placeholder="Search Here">
               <button class="btn btn-outline-primary ml-2 mt-2" type="button">Search</button> 
                </form>
            </div>
                
        </div>
    </nav>
    
    <div class="container">
    {% block body_content %}
    <!--outside this block gets inherited by other templates.<-->
    {% endblock %}
    </div>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rTttps://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> 
</body> 
</html>

templates/basicApp/base.html
<html>
<head>
    
    <meta charset="utf-8">
    <title>Navbar</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
<body>
    
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark"> <!-- navbar-dark and bg-dark are for navbar color, navbar expand-sm is used so that all the items are visible till the small screen, doesn't work for small screen -->
        <div class="container">
  <a class="navbar-brand" href="#">Navbar</a>
            
            <button class="navbar-toggler" data-toggle="collapse" aria-controls="togglebutton" data-target="#togglebutton">  
                <!-- for nav items to be seen on small screen, add an icon (burger item) using button and put a class in span tag, but still links won't work, so we add data-toggle and data-target element in button tag which uses js library-->
                
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="togglebutton"> <!--  don't be seen as a list in downside-->
            <ul class="navbar-nav mr-auto"> <!-- margin left automatically puts items on the left side. -->
            <li class="nav-item"><a href="{% url 'admin:index' %}" class="nav-link" >Admin</a></li> 
     <!-- specify nav links for merge in navbar, otherwise they will be visible as a simple blue links. -->
            <li class="nav-item"><a href="{% url 'basicApp:registration' %}" class="nav-link" >Register Here</a></li>
           {% if user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'logout' %}" class='nav-link'>LogOUT</a></li>
                
            {% else %}
                <li class="nav-item"><a href="{% url 'basicApp:login' %}" class='nav-link'>LogIN</a></li>     
            {% endif %}
                <!-- dropdown menu in navbar -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="id_1" data-toggle="dropdown">Dropdown Menu</a>
                <div class="dropdown-menu" id="id_1">
                    <a class="dropdown-item" href="https://www.google.co.in">Go to Google</a>
                    <a class="dropdown-item" href="https://www.youtube.com">Go to Youtube</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'index' %}">Return to Homepage</a>
                    
            <li class="nav-item"><a class="nav-link disabled">Don't touch </a></li>
                </div>
                </li>
            </ul>
                
            <form class="form-inline">
                <input class="form-control mt-2 " type="search" placeholder="Search Here">
               <button class="btn btn-outline-primary ml-2 mt-2" type="button">Search</button> 
                </form>
            </div>
                
        </div>
    </nav>
    
    <div class="container">
    {% block body_block %}
    <!--outside this block gets inherited by other templates.<-->
    {% endblock %}
    </div>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rTttps://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> 
</body> 
</html>

templates/basicApp/index.html
<!DOCTYPE html>
{% extends 'basicApp/base.html' %}
{% load staticfiles %}

{% block body_block %}
<div class="jumbotron">
    <h2> Welcome to the INDEX page.</h2>
</div>
{% endblock %}

templates/basicApp/login.html
{% extends 'basicApp/base.html' %}
{% block body_block %}
<div class='jumbotron'>
<h1>Please Login</h1>
    <form action="{% url 'basicApp:login' %}" method="post">
    {% csrf_token %}
        <label for='username'>UserName: </label>
        <input type="text" name='username' placeholder="Enter username.">
        <label for="password">Password: </label>
        <input type='password' name="password" placeholder="Enter Password.">
        <input type="submit" value='LogIn'>
    </form>

</div>
{% endblock %}

templates/basicApp/registration.html
<!DOCTYPE html>
{% extends 'basicApp/base.html' %}
{% load staticfiles %}

{% block body_block %}
<div class="jumbotron">
    {% if isRegistered %}
    <h2> Thank you for the registration. </h2> 
    {% else %}
    <h2> Register here!</h2>
    <hr>
    <h3> Please Fill Up The Form Below: </h3>
    <!-- Add the enctype to load the image. -->
    <form method="post" enctype="multipart/form-data">  
        {% csrf_token %}
        {{ userForm.as_p }}
        {{ profileForm.as_p }}
        <input type="submit" class="btn btn-primary" value="register">
    </form>
    {% endif %}
</div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
{% extends 'basicApp/base.html' %}
{% load staticfiles %}

{% block body_block}
<div class="jumbotron">
    <h2> Welcome to the INDEX page.</h2>
</div>
{% endblock %}

templates/registration.html
<!DOCTYPE html>
{% extends 'basicApp/base.html' %}
{% load staticfiles %}

{% block body_block}
<div class="jumbotron">
    {% if %}
    <h2> Thank you for the registration. </h2> 
    {% else %}
    <h2> Register here!</h2>
    <hr>
    <h3> Please Fill Up The Link Below: </h3>
    <!-- Add the enctype to load the image. -->
    <form action="" method="post" enctype="multipart/form-data">  
        {% csrf_token %}
        {{ userForm.as_p }}
        {{% profileForm.as_p %}}
        <input type="button" class="btn btn-primary" value="register">
    </form>
    {% endif %}
</div>
{% endblock %}